/var/www/gambler/logs/*.log {
    weekly
    missingok
    rotate 52
    compress
    delaycompress
    notifempty
    create 640 gambler users
    sharedscripts
    postrotate
        if [ -f /var/run/gambler.pid ]; then
            kill -USR1 $(cat /var/run/gambler.pid)
        fi
    endscript
}
